require('../views/md.html')
require('../views/404.html')
require('../views/index.html')
require('../views/install.html')
require('../views/fhirbase.html')
require('../views/frontend.html')
require('../views/application.html')
